# Generated by Django 5.2.6 on 2026-09-21 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Sales', 'Sales'), ('Customer', 'Customer'), ('Product', 'Product'), ('Regional', 'Regional'), ('Marketing', 'Marketing'), ('Financial', 'Financial'), ('Returns', 'Returns'), ('Operational', 'Operational'), ('General', 'General')], default='General', max_length=50)),
                ('description', models.TextField()),
                ('supporting_insight', models.TextField(blank=True, default='')),
                ('recommended_action', models.TextField()),
                ('expected_outcome', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('impact_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('confidence', models.FloatField(default=0, help_text='Recommendation confidence percentage from 0 to 100.')),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='New', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='data_management.datasetversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'dataset_version'], name='decision_in_dataset_6c7499_idx'), models.Index(fields=['category'], name='decision_in_categor_4003de_idx'), models.Index(fields=['priority'], name='decision_in_priorit_d546d9_idx'), models.Index(fields=['status'], name='decision_in_status_1eeca7_idx'), models.Index(fields=['created_at'], name='decision_in_created_c8b1b7_idx')],
            },
        ),
    ]
