# Generated by Django 5.2.6 on 2026-09-22 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIfSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='What-If Simulation', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('assumptions', models.JSONField(blank=True, default=dict, help_text='Stores the assumptions and changes used for the simulation.')),
                ('baseline_results', models.JSONField(blank=True, default=dict, help_text='Stores the original dataset results before simulation.')),
                ('simulated_results', models.JSONField(blank=True, default=dict, help_text='Stores the calculated results after applying simulation assumptions.')),
                ('result_summary', models.JSONField(blank=True, default=dict, help_text='Stores summarized changes between baseline and simulated results.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='what_if_simulations', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_if_simulations', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_if_simulations', to='data_management.datasetversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'dataset_version'], name='decision_in_dataset_e902b2_idx'), models.Index(fields=['created_by'], name='decision_in_created_2da50a_idx'), models.Index(fields=['status'], name='decision_in_status_a655a4_idx'), models.Index(fields=['created_at'], name='decision_in_created_1a8612_idx')],
            },
        ),
    ]
