# Generated by Django 5.2.6 on 2026-09-22 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0002_whatifsimulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Business Scenario', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scenario_type', models.CharField(default='Custom', help_text='Type of business scenario being planned.', max_length=50)),
                ('assumptions', models.JSONField(blank=True, default=dict, help_text='Stores the assumptions and business changes used for the scenario.')),
                ('baseline_results', models.JSONField(blank=True, default=dict, help_text='Stores baseline results from the selected dataset version.')),
                ('projected_results', models.JSONField(blank=True, default=dict, help_text='Stores projected results after applying the scenario assumptions.')),
                ('comparison_results', models.JSONField(blank=True, default=dict, help_text='Stores the comparison between baseline and projected results.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_plans', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_plans', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_plans', to='data_management.datasetversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'dataset_version'], name='decision_in_dataset_fb84b4_idx'), models.Index(fields=['created_by'], name='decision_in_created_e1b2b6_idx'), models.Index(fields=['scenario_type'], name='decision_in_scenari_910515_idx'), models.Index(fields=['status'], name='decision_in_status_a83615_idx'), models.Index(fields=['created_at'], name='decision_in_created_1e2eff_idx')],
            },
        ),
    ]
