# Generated by Django 5.2.6 on 2026-09-22 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0003_scenarioplanning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Sales', 'Sales'), ('Customer', 'Customer'), ('Product', 'Product'), ('Regional', 'Regional'), ('Marketing', 'Marketing'), ('Financial', 'Financial'), ('Returns', 'Returns'), ('Operational', 'Operational'), ('General', 'General')], default='General', max_length=50)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('description', models.TextField()),
                ('trigger_type', models.CharField(default='Threshold', help_text='Type of business condition that triggered the alert.', max_length=100)),
                ('metric_name', models.CharField(blank=True, default='', max_length=100)),
                ('metric_value', models.FloatField(default=0)),
                ('threshold_value', models.FloatField(default=0)),
                ('comparison_operator', models.CharField(default='>', max_length=10)),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('New', 'New'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='New', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_alerts', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to='data_management.datasetversion')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['dataset', 'dataset_version'], name='decision_in_dataset_133a1b_idx'), models.Index(fields=['category'], name='decision_in_categor_78412d_idx'), models.Index(fields=['severity'], name='decision_in_severit_bfc54c_idx'), models.Index(fields=['status'], name='decision_in_status_676f41_idx'), models.Index(fields=['detected_at'], name='decision_in_detecte_6ca8a9_idx')],
            },
        ),
    ]
