# Generated by Django 5.2.6 on 2026-09-22 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0004_businessalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('action', models.TextField(help_text='The specific business action that should be performed.')),
                ('expected_outcome', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Sales', 'Sales'), ('Customer', 'Customer'), ('Product', 'Product'), ('Regional', 'Regional'), ('Marketing', 'Marketing'), ('Financial', 'Financial'), ('Returns', 'Returns'), ('Operational', 'Operational'), ('General', 'General')], default='General', max_length=50)),
                ('source_type', models.CharField(choices=[('Recommendation', 'Recommendation'), ('Alert', 'Alert'), ('Manual', 'Manual')], default='Manual', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='decision_intelligence.businessalert')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_action_items', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='data_management.datasetversion')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='decision_intelligence.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'dataset_version'], name='decision_in_dataset_c64fda_idx'), models.Index(fields=['created_by'], name='decision_in_created_b4f73b_idx'), models.Index(fields=['assigned_to'], name='decision_in_assigne_a503e8_idx'), models.Index(fields=['recommendation'], name='decision_in_recomme_29fbe5_idx'), models.Index(fields=['alert'], name='decision_in_alert_i_e08b28_idx'), models.Index(fields=['source_type'], name='decision_in_source__2ff596_idx'), models.Index(fields=['category'], name='decision_in_categor_3a3343_idx'), models.Index(fields=['priority'], name='decision_in_priorit_038308_idx'), models.Index(fields=['status'], name='decision_in_status_4f9014_idx'), models.Index(fields=['due_date'], name='decision_in_due_dat_166a7c_idx'), models.Index(fields=['created_at'], name='decision_in_created_581326_idx')],
            },
        ),
    ]
