# Generated by Django 5.2.6 on 2026-09-22 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        ('decision_intelligence', '0005_actionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionImpactAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Sales', 'Sales'), ('Customer', 'Customer'), ('Product', 'Product'), ('Regional', 'Regional'), ('Marketing', 'Marketing'), ('Financial', 'Financial'), ('Returns', 'Returns'), ('Operational', 'Operational'), ('General', 'General')], default='General', max_length=50)),
                ('metric_name', models.CharField(blank=True, default='', max_length=100)),
                ('baseline_value', models.FloatField(default=0)),
                ('expected_value', models.FloatField(default=0)),
                ('actual_value', models.FloatField(default=0)),
                ('expected_change', models.FloatField(default=0, help_text='Expected percentage change.')),
                ('actual_change', models.FloatField(default=0, help_text='Actual percentage change.')),
                ('impact_value', models.FloatField(default=0, help_text='Difference between actual and baseline value.')),
                ('impact_percentage', models.FloatField(default=0, help_text='Percentage impact compared with the baseline.')),
                ('impact_type', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative'), ('Mixed', 'Mixed')], default='Neutral', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Monitoring', 'Monitoring'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('analysis_notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_analyses', to='decision_intelligence.actionitem')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_analyses', to='decision_intelligence.businessalert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_impact_analyses', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_impact_analyses', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_impact_analyses', to='data_management.datasetversion')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_analyses', to='decision_intelligence.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'dataset_version'], name='decision_in_dataset_996092_idx'), models.Index(fields=['created_by'], name='decision_in_created_6432da_idx'), models.Index(fields=['action_item'], name='decision_in_action__eac174_idx'), models.Index(fields=['recommendation'], name='decision_in_recomme_6e514a_idx'), models.Index(fields=['alert'], name='decision_in_alert_i_b48380_idx'), models.Index(fields=['category'], name='decision_in_categor_670988_idx'), models.Index(fields=['metric_name'], name='decision_in_metric__b96845_idx'), models.Index(fields=['impact_type'], name='decision_in_impact__3bc9c7_idx'), models.Index(fields=['status'], name='decision_in_status_e36833_idx'), models.Index(fields=['created_at'], name='decision_in_created_1c472b_idx')],
            },
        ),
    ]
