# Generated by Django 5.2.6 on 2026-09-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contactmessage_is_read_contactmessage_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
    ]
