# Generated by Django 5.2.6 on 2026-09-11 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dataset_type', models.CharField(choices=[('Sales', 'Sales'), ('Customers', 'Customers'), ('Products', 'Products'), ('Regional', 'Regional'), ('Marketing', 'Marketing'), ('Financial', 'Financial'), ('Returns', 'Returns')], max_length=30)),
                ('file', models.FileField(upload_to='datasets/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('total_columns', models.PositiveIntegerField(default=0)),
                ('missing_values', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
