# Generated by Django 5.2.6 on 2026-09-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version_type', models.CharField(choices=[('Original', 'Original'), ('Cleaned', 'Cleaned'), ('Validated', 'Validated'), ('Transformed', 'Transformed'), ('Manual', 'Manual')], default='Original', max_length=30)),
                ('file', models.FileField(upload_to='dataset_versions/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('total_columns', models.PositiveIntegerField(default=0)),
                ('missing_values', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='data_management.dataset')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
                'unique_together': {('dataset', 'version_number')},
            },
        ),
    ]
