# Generated by Django 5.2.6 on 2026-09-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_datasetversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Validated', 'Validated'), ('Profiled', 'Profiled'), ('Quality Checked', 'Quality Checked'), ('Cleaned', 'Cleaned'), ('Transformed', 'Transformed'), ('Analytics Ready', 'Analytics Ready')], max_length=40)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Warning', 'Warning'), ('Failed', 'Failed')], default='Success', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='data_management.dataset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
