# Generated by Django 5.2.6 on 2026-09-19 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('Future Trends', 'Future Trends'), ('Forecasting', 'Forecasting'), ('Anomaly Detection', 'Anomaly Detection'), ('Root Cause Analysis', 'Root Cause Analysis'), ('Customer Segmentation', 'Customer Segmentation'), ('Churn Risk', 'Churn / Risk Analysis'), ('Opportunity Detection', 'Opportunity Detection')], max_length=100)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Running', max_length=30)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insight_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_runs', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_runs', to='data_management.datasetversion')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_column', models.CharField(max_length=255)),
                ('metric_column', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=30)),
                ('trend_direction', models.CharField(max_length=50)),
                ('trend_strength', models.CharField(max_length=50)),
                ('percentage_change', models.FloatField(blank=True, null=True)),
                ('average_value', models.FloatField(blank=True, null=True)),
                ('minimum_value', models.FloatField(blank=True, null=True)),
                ('maximum_value', models.FloatField(blank=True, null=True)),
                ('first_period_value', models.FloatField(blank=True, null=True)),
                ('latest_period_value', models.FloatField(blank=True, null=True)),
                ('recent_direction', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('chart_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trend_result', to='advanced_insights.insightrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
