# Generated by Django 5.2.6 on 2026-09-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendresult',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
    ]
