# Generated by Django 5.2.6 on 2026-09-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_insights', '0002_alter_trendresult_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_column', models.CharField(max_length=255)),
                ('metric_column', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=50)),
                ('horizon', models.PositiveIntegerField(default=3)),
                ('historical_periods', models.PositiveIntegerField(default=0)),
                ('forecast_periods', models.PositiveIntegerField(default=0)),
                ('last_actual_value', models.FloatField(blank=True, null=True)),
                ('first_forecast_value', models.FloatField(blank=True, null=True)),
                ('latest_forecast_value', models.FloatField(blank=True, null=True)),
                ('forecast_change_percentage', models.FloatField(blank=True, null=True)),
                ('average_forecast_value', models.FloatField(blank=True, null=True)),
                ('minimum_forecast_value', models.FloatField(blank=True, null=True)),
                ('maximum_forecast_value', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('chart_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_result', to='advanced_insights.insightrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
