# Generated by Django 5.2.6 on 2026-09-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_insights', '0003_forecastresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_column', models.CharField(blank=True, max_length=255)),
                ('metric_column', models.CharField(max_length=255)),
                ('detection_method', models.CharField(choices=[('Z-Score', 'Z-Score')], default='Z-Score', max_length=50)),
                ('threshold', models.FloatField(default=2.5)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('normal_records', models.PositiveIntegerField(default=0)),
                ('anomaly_count', models.PositiveIntegerField(default=0)),
                ('anomaly_percentage', models.FloatField(default=0)),
                ('average_value', models.FloatField(blank=True, null=True)),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
                ('minimum_value', models.FloatField(blank=True, null=True)),
                ('maximum_value', models.FloatField(blank=True, null=True)),
                ('highest_anomaly_value', models.FloatField(blank=True, null=True)),
                ('lowest_anomaly_value', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('chart_data', models.JSONField(blank=True, default=list)),
                ('anomaly_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_result', to='advanced_insights.insightrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
