# Generated by Django 5.2.6 on 2026-09-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_insights', '0004_anomalyresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCauseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_column', models.CharField(max_length=255)),
                ('date_column', models.CharField(blank=True, max_length=255)),
                ('dimension_column', models.CharField(blank=True, max_length=255)),
                ('analysis_type', models.CharField(default='Contribution Analysis', max_length=50)),
                ('target_period', models.CharField(blank=True, max_length=100)),
                ('comparison_period', models.CharField(blank=True, max_length=100)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('comparison_value', models.FloatField(blank=True, null=True)),
                ('change_value', models.FloatField(blank=True, null=True)),
                ('change_percentage', models.FloatField(blank=True, null=True)),
                ('primary_cause', models.CharField(blank=True, max_length=255)),
                ('primary_cause_contribution', models.FloatField(blank=True, null=True)),
                ('cause_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('cause_data', models.JSONField(blank=True, default=list)),
                ('chart_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_cause_result', to='advanced_insights.insightrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
