# Generated by Django 5.2.6 on 2026-09-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_insights', '0005_rootcauseresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegmentationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_column', models.CharField(max_length=255)),
                ('metric_columns', models.JSONField(blank=True, default=list)),
                ('segmentation_method', models.CharField(default='RFM', max_length=100)),
                ('number_of_segments', models.PositiveIntegerField(default=4)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('segmented_customers', models.PositiveIntegerField(default=0)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('largest_segment', models.CharField(blank=True, max_length=255)),
                ('largest_segment_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('segment_data', models.JSONField(blank=True, default=list)),
                ('customer_data', models.JSONField(blank=True, default=list)),
                ('chart_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segmentation_result', to='advanced_insights.insightrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
