# Generated by Django 5.2.6 on 2026-09-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_insights', '0006_customersegmentationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnRiskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_column', models.CharField(max_length=255)),
                ('date_column', models.CharField(blank=True, max_length=255)),
                ('metric_columns', models.JSONField(blank=True, default=list)),
                ('risk_method', models.CharField(default='Activity-Based Risk Analysis', max_length=100)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('assessed_customers', models.PositiveIntegerField(default=0)),
                ('high_risk_customers', models.PositiveIntegerField(default=0)),
                ('medium_risk_customers', models.PositiveIntegerField(default=0)),
                ('low_risk_customers', models.PositiveIntegerField(default=0)),
                ('high_risk_percentage', models.FloatField(default=0)),
                ('average_risk_score', models.FloatField(default=0)),
                ('highest_risk_customer', models.CharField(blank=True, max_length=255)),
                ('highest_risk_score', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('risk_data', models.JSONField(blank=True, default=list)),
                ('customer_data', models.JSONField(blank=True, default=list)),
                ('chart_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='churn_risk_result', to='advanced_insights.insightrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
