# Generated by Django 5.2.6 on 2026-09-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_insights', '0007_churnriskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_column', models.CharField(blank=True, max_length=255)),
                ('value_column', models.CharField(blank=True, max_length=255)),
                ('date_column', models.CharField(blank=True, max_length=255)),
                ('opportunity_method', models.CharField(blank=True, max_length=255)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('total_opportunities', models.PositiveIntegerField(default=0)),
                ('high_opportunities', models.PositiveIntegerField(default=0)),
                ('medium_opportunities', models.PositiveIntegerField(default=0)),
                ('low_opportunities', models.PositiveIntegerField(default=0)),
                ('opportunity_percentage', models.FloatField(default=0)),
                ('average_opportunity_score', models.FloatField(default=0)),
                ('highest_opportunity', models.CharField(blank=True, max_length=255)),
                ('highest_opportunity_score', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('opportunity_data', models.JSONField(blank=True, default=list)),
                ('opportunity_details', models.JSONField(blank=True, default=list)),
                ('chart_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_detection_result', to='advanced_insights.insightrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
