# Generated by Django 5.2.6 on 2026-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
    ]
