# Generated by Django 5.2.6 on 2026-09-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0003_datasetactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('Automated', 'Automated'), ('Custom', 'Custom')], default='Automated', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Stores the report configuration, filters, metrics, dimensions, date range, and chart settings.')),
                ('generated_data', models.JSONField(blank=True, default=dict, help_text='Stores the generated report summary, KPIs, tables, trends, and other report results.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generating', 'Generating'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='data_management.datasetversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/exports/')),
                ('status', models.CharField(choices=[('Generating', 'Generating'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Generating', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reporting.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Stores selected columns, metrics, dimensions, filters, date range, charts, and layout settings.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to='data_management.dataset')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to='data_management.datasetversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='reporting_c_owner_i_df0ce2_idx'), models.Index(fields=['dataset', 'dataset_version'], name='reporting_c_dataset_62f49e_idx'), models.Index(fields=['created_at'], name='reporting_c_created_8c05e7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['owner', 'created_at'], name='reporting_r_owner_i_6b3c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['dataset', 'dataset_version'], name='reporting_r_dataset_3609b3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reporting_r_report__5d34ee_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reporting_r_status_b3f463_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['report', 'export_type'], name='reporting_r_report__2d5d89_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['status'], name='reporting_r_status_c31b20_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['created_at'], name='reporting_r_created_286de4_idx'),
        ),
    ]
